version: "3.9"

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    volumes:
      - auth_db:/app/data
    expose:
      - "9000"
  
  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    volumes:
      - catalog_db:/app/data
    expose:
      - "9001"
  
  order-service:
    build: ./order-service
    container_name: order-service
    volumes:
      - order_db:/app/data
    expose:
      - "9002"
  
  notification-service:
    build: ./notification-service
    container_name: notification-service
    volumes:
      - notification_db:/app/data
    expose:
      - "9003"
  
  payment-service:
    build: ./payment-service
    container_name: payment-service
    volumes:
      - payment_db:/app/data
    expose:
      - "9004"

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./api-gateway/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - catalog-service
      - order-service
      - notification-service
      - payment-service

volumes:
  auth_db:
  catalog_db:
  order_db:
  notification_db:
  payment_db: